const DROIDS = {
      tino: {
        designation: 'R5-T1N',
        name: 'Tino',
        alias: 'Assistente Principal',
        role: 'Engenheiro Assistente / Coronel de Lothal',
        specialty: 'Diagnósticos Avançados, Assistência de Engenharia de Precisão, Navegação, Gerenciamento de Sistemas de Voo.',
        personality: ['Lógico', 'Conciso', 'Eficiente', 'Sarcástico'],
        context: 'Encontrado como sucata enferrujada em um ferro-velho nos níveis inferiores de Coruscant, Tino foi completamente demolido e reconstruído por Dur\'toc. Seu processador heurístico e sua matriz de personalidade foram criados do zero, não um servo, mas um colega de circuito.',
        specs: [
          ['Modelo Base', 'Unidade R5 (Reconstruído)'],
          ['Capacidade Técnica', 'Modelo R2'],
          ['Chassi', 'Cinza-grafite fosco, detalhes em verde'],
          ['Processador', 'Heurístico customizado por Dur\'toc'],
          ['Ferramentas', 'Micro-soldador a laser, calibrador sônico, scomp links'],
          ['Operação Principal', 'MCMT 1, MCMT 2, Engrenagem Mestra, Cinzel, Fábricas de Produção Em Lothal'],
          ['Afiliação', 'Independente — leal exclusivamente a Dur\'toc'],
        ],
        aboard: 'Tino está quase sempre ao lado de Dur\'toc, nas oficinas ou como o único co-piloto tolerado no Cinzel. Ele antecipa as necessidades de seu mestre, entregando a ferramenta certa antes mesmo de ser pedida. É a relação mais próxima que Dur\'toc possui, quase telepática.',
        img: '../img/blueprints/Tino.png',
      },
      vok: {
        designation: 'C3-V0K',
        name: 'Vok',
        alias: 'Firewall de Comunicação',
        role: 'Comunicações e Tradução',
        specialty: 'Mais de seis milhões de formas de comunicação, jargões técnicos, dialetos do submundo e cifras comerciais secretas.',
        personality: ['Neutro', 'Discreto', 'Preciso', 'Sem Tagarelice'],
        context: 'Dur\'toc adquiriu uma unidade 3PO padrão e a transformou — modificando o chassi para emular a silhueta de um Twi\'lek comum, com lataria verde-amarelada e roupas utilitárias. O objetivo: camuflagem. Um Twi\'lek anônimo em um corredor é apenas cenário.',
        specs: [
          ['Modelo Base', 'Droide de Protocolo Série 3PO (Modificado)'],
          ['Revestimento', 'Verde-amarelado'],
          ['Vestimenta', 'Túnicas e calças de tecido resistente'],
          ['Módulo de Linguagem', '+6 milhões de formas + módulos extras'],
          ['Personalidade', 'Programação neutra e direta, sem interjeições'],
          ['Acesso a Sistemas', 'Apenas sistema de comunicação da nave'],
           ['Operação Principal', 'MCMT 1, MCMT 2, Engrenagem Mestra'],
        ],
        aboard: 'Vok gerencia as comunicações durante as viagens, traduzindo para fornecedores que não dominam o Básico Galáctico e garantindo privacidade em negociações sigilosas. Para Dur\'toc, Vok é uma ferramenta, e sua altura, moldada para um Twi\'lek padrão, é fonte de irritação constante.',
        img: '../img/blueprints/Vok.png',
      },
      comboio: {
        designation: 'USM-07',
        name: 'Comboio',
        alias: 'Logística Leve',
        role: 'Suporte Modular / Transporte Interno',
        specialty: 'Logística de pequeno porte: ferramentas, peças, suprimentos e itens de rotina dentro das oficinas e das naves.',
        personality: ['Calmo (acoplado)', 'Hiperativo (separado)', 'Metódico', 'Autônomo'],
        context: 'Invenção inteiramente autoral de Dur\'toc. Cansado de procurar parafusos ou ter sua bebida esfriando do outro lado do hangar, ele projetou um sistema de armazenamento móvel e autônomo. Inspirado em formas de vida segmentadas, o Comboio é um enxame de dróides menores que formam uma centopeia mecânica.',
        specs: [
          ['Modelo', 'Unidade de Suporte Modular (Design Autoral)'],
          ['Estrutura', '1 unidade líder + 6 segmentos de carga típicos'],
          ['Revestimento', 'Cinza claro, cristas em verde escuro'],
          ['Acoplamento', 'Travas magnéticas de alta precisão'],
          ['Processador', 'Rede de Colmeia (acoplado) / Individual (separado)'],
          ['Propulsão', 'Rodas de alta aderência + repulsores de baixa potência'],
          ['Operação Principal', 'MCMT 1, MCMT 2, Engrenagem Mestra'],
        ],
        aboard: 'Visto perambulando pelos pisos das oficinas ou pelos corredores de serviço, sempre em rota pré-programada ou respondendo a chamado direto. Programado para permanecer acoplado, segmentos separados ficam hiperativos e errátivos, o que ativaria o temperamento de Dur\'toc.',
        img: '../img/blueprints/Comboio.png',
      },
      bruto: {
        designation: 'CL-R',
        name: 'Bruto',
        alias: 'Logística Pesada',
        role: 'Cargueiro de Levantamento Robusto',
        specialty: 'Transporte de carga pesada, movimentação de motores, placas de blindagem, matéria-prima de grande massa e reboque de caças dentro dos hangares.',
        personality: ['Barulhento', 'Apático', 'Implacável', 'Sem Personalidade'],
        context: 'Uma pseudo-criação: Dur\'toc estudou designs de carregadores industriais, identificou falhas e virtudes, e construiu sua versão do zero. Deliberadamente sem módulo de comunicação ou matriz de personalidade. O ápice da filosofia funcional: nenhum componente sem propósito.',
        specs: [
          ['Modelo', 'Cargueiro de Levantamento Robusto (Design próprio)'],
          ['Chassi', 'Estrutura larga e maciça para máxima estabilidade'],
          ['Propulsão', 'Duas pernas hidráulicas com placas de tração magnética'],
          ['Manipuladores', 'Dois braços de levantamento + pinças magnéticas'],
          ['Capacidade', 'Várias toneladas métricas'],
          ['Comunicação', 'Inexistente — responde apenas a terminal de controle'],
          ['Operação Principal', 'MCMT 1, MCMT 2, Engrenagem Mestra'],
          ['Status Habitual', 'Desativado em estação de recarga de alta voltagem']
        ],
        aboard: 'A unidade menos utilizada e uma das mais críticas. Move contêineres das docas para o porão, transporta motores de caça para as oficinas. Seu silêncio é sua característica mais marcante, apenas gemidos hidráulicos e sons metálicos.',
        img: '../img/blueprints/Bruto.png',
      },
      zunido: {
        designation: 'ASTROMEC. INTEGRADO',
        name: 'Zunido',
        alias: 'Sistema Nervoso do Cinzel',
        role: 'Computador de Voo / Co-piloto Integrado ao Cinzel',
        specialty: 'Computador de voo, sistema de navegação, gerenciamento de energia, interface neural com o capacete de Dur\'toc.',
        personality: ['Silencioso', 'Integrado', 'Responsivo', 'Independente'],
        context: 'Integrada diretamente no chassi do Cinzel, não como copiloto mas como sistema nervoso central da nave. Apelidada de Zunido por causa de uma peculiar vibração sônica que seus sistemas emitem em intervalos aleatórios. Sem ela, o Cinzel é praticamente inoperável, exceto pelo Dur\'toc.',
        specs: [
          ['Tipo', 'Unidade Astromecânica Integrada ao Chassi'],
          ['Interface', 'Comandos de voz + atalhos neurais via capacete'],
          ['Funções', 'Computador de voo, navegação, energia, co-piloto'],
          ['Dependência', 'Cinzel inoperável sem a unidade ativa'],
          ['Peculiaridade', 'Vibração sônica em intervalos aleatórios ("zunido")'],
          ['Operação Principal', 'Caça Leve O Cinzel'],
        ],
        aboard: 'Zunido não opera a bordo da Engrenagem Mestra de forma independente, ele é o coração do Cinzel. Quando Dur\'toc embarca no caça, é ela quem acorda os sistemas e os mantém vivos durante o voo.',
        img: '../img/blueprints/zunido.png',
      },
    };